language: node_js

cache:
  directories:
    - ~/.npm
    - "node_modules"

node_js:
  - '13'

services:
  - mongodb
  - redis-server

git:
  depth: 3

branches:
  only:
    - master

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
  - yarn
  - yarn seed
  - yarn test
  - yarn report-coverage

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
