version: '3.5'

services:
  coeus:
    container_name: hybrid
    restart: always
    image: api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo/hybrid
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
      - NODE_ENV=production
      - PORT=3000
    links:
      - redis
      - mongo
    tty: true
  mongo:
    image: mongo:latest
    container_name: hybrid-mongo
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo:/data/db
  mongo-seed:
    image: stefanwalther/mongo-seed
    container_name: mongo-seed
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - ./data:/data
    depends_on:
      - mongo
    command: [
      "mongoimport --host mongo --port 27017 --db hybrid --mode upsert --type json --file data/users.json --jsonArray"
    ]
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

volumes:
  mongo:
  redis:
